apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  namespace: default
  labels:
    app: example-glusterfs-heketi
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "glusterfs-storage"
